name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to GitHub Packages
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.GITHUB_TOKEN }}
